### ISSUE TITLE
Re-classification of object gives error

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/marshall_webapp_wiki#113]
I made a typo in PS16dpm, z=7.13 instead of z=0.13 

But when I try to reclassify I get "Internal Server Error"

In general - need to check that a change in z then propogates to the abs peak mag recalculation

**Comment by thespacedoctor** [comment]
The database won't allow a second classification of the same object given on the same date as a previous classification. This is back to the issue of being able to edit object parameters directly in the marshall. I have fixed the issue in question:

http://www.pessto.org/marshall/transients/search?q=PS16dpm

but will leave this issue open

**Comment by smarttgit** [comment]
I updated SN2016enx, as it did not have a classification epoch. I added "at max" and I also set the redshift to 0.08 in the reclassification. 

The update went through and the epoch was added. But the redshift did not get updated to 0.08, it stayed at 0.078

**Comment by thespacedoctor** [comment]
Found the bug -- was due to the order the mysql query selects out the most recent classification. The redshift for SN2016enx, and all other reclassified objects for that matter, has been fixed.
