### ISSUE TITLE
Duplicate photometry points 

### ISSUE THREAD

**Issue by katemaguire** [thespacedoctor/marshall_webapp_wiki#127]
For SN2017nx, the photometry point from the PIKA group on the TNS appears to be duplicated with an Asiago name.

**Comment by katemaguire** [comment]
Points for AT2017ng seem funny too. Slightly different dates with same magnitude

**Comment by katemaguire** [comment]
AT2017mw

**Comment by katemaguire** [comment]
SN2017mu

**Comment by thespacedoctor** [comment]
Here's the SN2017nx example - the discovery mag is getting incorrectly re-associated with the classification date

![][20170208085737]

[20170208085737]: https://i.imgur.com/cJn3ff3.png

**Comment by thespacedoctor** [comment]
The import code has been corrected, 538 affected objects have had their data scrubbed of the incorrectly reported mags and all lightcurve plots regenerated. Here is SN2017nx:

![][20170208094118]

[20170208094118]: https://i.imgur.com/uhWP9SF.png

**Comment by thespacedoctor** [comment]
For AT2017mw == Gaia17afb the two data-points are both legitimate. On the Gaia source pages there is an Alert Mag, but also average mags for each Gaia spectrum. For Gaia17afb the one spectral mag == alert mag.

[Gaia17ahq](http://gsaweb.ast.cam.ac.uk/alerts/alert/Gaia17ahq/) is a better example where we have the alert mag + 2 spectral mags:

![][20170208095434]

[20170208095434]: https://i.imgur.com/HiZH4wK.png

**Comment by thespacedoctor** [comment]
Finally, AT2017ng == ASASSN-17bb. It seems the ASSASN team made a modification to the plain-text download of their SN transient listing in mid-december adding a extra character / line. This threw off my regex that parses the decimal day portion of the observation date. All 18 sources affected fix.
