### ISSUE TITLE
Change the plots - only 3 sigma limits (remove all points < 3 sigma)

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/marshall_webapp_wiki#133]
The lightcurve plots show detections which are less than 3 sigma. 

We should ONLY plot points which are >= 3 sigma significance and for all others plot the 3 sigma limits. 

This should be done on both the Marshall plots AND the ATLAS pages

This is very high priority - the highest priority from users (at Dublin meeting and also general feedback)

**Comment by thespacedoctor** [comment]
This was corrected but using 5𝜎 as the detection-limit. See #139 for details.

**Comment by smarttgit** [comment]
We should still plot the 3-sigma detections from the forced photometry (and the 3 sigma limits if the detections are less than 3 sigma) 

But can we define "discovery date" as the first 5 sigma detection

**Comment by thespacedoctor** [comment]
ok - a little 'hacky' within the code but very possible.

**Comment by thespacedoctor** [comment]
As agreed the discovery date is fixed as the first ATLAS detection to exceed 5𝜎, but the lightcurves show all measurements >3𝜎 as detections. For example:

![atlas17nzu with 3 sigma limits][atlas17nzu with 3 sigma limits 39014022184]

[atlas17nzu with 3 sigma limits 39014022184]: https://farm5.staticflickr.com/4746/39014022184_501bfb8f0f_o.png
