### ISSUE TITLE
Plot the lightcurves in calibrated flux as well as magnitudes

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/marshall_webapp_wiki#137]
It's often a lot better to look at the flux rather than the magnitude on the y-axis, particular when doing forced photometry. 

Let's investigate either 
1) Separate flux plots 
2) Combined mag and flux plots 

sjs to check the equations to use

**Comment by smarttgit** [comment]
Can you dig out the recipe that tphot uses to get mags from the params peakfit, major, minor etc and paste in here

**Comment by thespacedoctor** [comment]
First there is a refit of the brightest starts (S/N > 100) to give a median `apfit`, where each apfit is given as:

```
apfit=-2.5log(flux/(peakfit * major * minor))
```

Then the magnitude for each source is given as:

```
m=zp+apfit-2.5*log(peakfit * major * minor / dt)
```

Limiting magnitudes are given as 

```
m_lim=zp+apfit-2.5*log(dpeak * major * minor * SNR / dt)
```

Some definitions:

| Parameter  | Description | Unit |
| :------------ | :----------- |:----------- |
| x       | x central position  | pix, left pixel centre is 0.5 |
| y       | y central position  | pix, lower pixel centre is 0.5 |
| peakval | data value of the brightest pixel  | ADU |
| skyval  | robust estimate of the local sky  | ADU |
| peakfit | peak of the Waussian fit (in excess of sky)  | ADU |
| dpeak   | uncertainty in the Waussian peak  | ADU |
| skyfit  | sky value of the Waussian fit  | ADU |
| flux    | net aperture flux of this object  | ADU |
| dflux   | flux uncertainty  | ADU |
| major   | major axis FWHM (or trail length)  | pix |
| minor   | minor axis FWHM (or trail FWHM)  | pix |
| phi     | angle of major axis, CCW from x axis  | deg |
| err     | error flag | |
| chi/N   | $chi^2/N$  | |

**Comment by smarttgit** [comment]
Here's an example plot of using flux instead of mags 

ATLAS17nsw
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1224158591201613500/

Just converting the mag values (which are >=1 sigma) into fluxes. Since the mags are in AB system, the fluxes in erg/s/cm^2/Hz are from the calibrated mags : 

fnu = 10^(-1*(mag+48.6)/2.5) 

This is better for selecting young transients. You can easily see the non-detections, and the rise above the noise 

![fluxplot_atlas17nsw](https://user-images.githubusercontent.com/9849458/34261064-e2a4c330-e65f-11e7-9a94-60d27980f09f.png)

**Comment by thespacedoctor** [comment]
Agreed - that looks much more informative. Will get the marshall plots converted.

**Comment by smarttgit** [comment]
Now, we want to calculate these flux f_nu values also for all points, even those with -ve flux and those which are < 1 sigma. 

So combining 
```
m=zp+apfit-2.5*log(peakfit * major * minor / dt)
```
with the definition for an AB mag 

```
m = -2.5 log(f_nu) -48.60 
```
gives 

```
 -2.5 log(f_nu) -48.60  = zp+apfit-2.5*log(peakfit * major * minor / dt)
 -2.5 log(f_nu) -48.60  = zp  - 2.5*log(10^(apfit/-2.5) * peakfit * major * minor / dt)
```

and 
```
f_nu = 10^((48.6 + ZP)/-2.5)) * [ 10^(apfit/-2.5) * peakfit * major * minor / dt]
```
For the errors :  is there a recipe in tphot that produces a flux error ?  Or we can just use SNR to divide into the second term in brackets.  

This equation also allows for the flux to be plotted as zero or negative (an advantage over using mags). 

ATLAS pages : we should have both the mag plots and flux plots 

Marshall : Dave can you experiment with presentation. The mag plots are still useful since nobody really has in mind what 2x10^-27 actually means ! And mags still needed. 
Either a righthand scale that has mags. Or perhaps just two plots side by side, which pop up when clicked. One for mags and one for flux

**Comment by thespacedoctor** [comment]
tphot produces `dpeak` which is the uncertainty in the Waussian fit (peakfit). We can use this - Ken has been recording this value in the database.

**Comment by smarttgit** [comment]
ok, that should work - that is the only uncertainty I think that enters the equation

**Comment by thespacedoctor** [comment]
I think I've now updated the ATLAS forced photometry import to collect all of the relevant values needed to generate these plots within the marshall. Here's the query I'm using to pull out the data:

```sql
SELECT 
    CONCAT('INSERT into fs_atlas_forced_phot (atlas_object_id, atlas_designation,mjd_obs,filter,mag,dm,snr,zp,limiting_mag,raDeg, decDeg, peakval, skyval, peakfit, dpeak, skyfit, flux, dflux, chin, major, minor, snrdet, snrlimit, wpflx, dwpflx, texp, expname ) values (',
            o.id,
            ',"',
            atlas_designation,
            '",',
            mjd_obs,
            ',"',
            filter,
            '",',
            p.mag,
            ',',
            dm,
            ',',
            snr,
            ',',
            zp,
            ',',
            limiting_mag,
            ',',
            o.ra,
            ',',
            o.dec,
            ',',
            peakval,
            ',',
            skyval,
            ',',
            peakfit,
            ',',
            dpeak,
            ',',
            skyfit,
            ',',
            flux,
            ',',
            dflux,
            ',',
            p.chin,
            ',',
            p.major,
            ',',
            p.minor,
            ',',
            snrdet,
            ',',
            snrlimit,
            ',',
            wpflx,
            ',',
            dflx,
            ',',
            texp,
            ',"',
            expname,
            '") ON DUPLICATE KEY UPDATE atlas_object_id=',
            o.id,
            ',atlas_designation="',
            atlas_designation,
            '",mjd_obs=',
            mjd_obs,
            ',filter="',
            filter,
            '",mag=',
            p.mag,
            ',dm=',
            dm,
            ',snr=',
            snr,
            ',zp=',
            zp,
            ',limiting_mag=',
            limiting_mag,
            ',raDeg=',
            o.ra,
            ',decDeg=',
            o.dec,
            ',peakval=',
            peakval,
            ',skyval=',
            skyval,
            ',peakfit=',
            peakfit,
            ',dpeak=',
            dpeak,
            ',skyfit=',
            skyfit,
            ',flux=',
            flux,
            ',dflux=',
            dflux,
            ',chin=',
            p.chin,
            ',major=',
            p.major,
            ',minor=',
            p.minor,
            ',snrdet=',
            snrdet,
            ',snrlimit=',
            snrlimit,
            ',wpflx=',
            wpflx,
            ',dwpflx=',
            dflx,
            ',texp=',
            texp,
            ',expname="',
            expname,
            '";')
FROM
    atlas_forced_photometry p,
    atlas_diff_objects o,
    atlas_metadataddc d,
    atlas_detectionsddc c
WHERE
    p.atlas_object_id = o.id
        AND c.atlas_object_id = o.id
        AND d.obs = p.expname
        AND p.mag IS NOT NULL
        AND dm IS NOT NULL
        AND snr IS NOT NULL
        AND p.date_inserted > DATE_SUB(NOW(), INTERVAL 7 DAY)
GROUP BY CONCAT(p.atlas_object_id, mjd_obs)
ORDER BY mjd_obs;
```

**Comment by thespacedoctor** [comment]
Hitting a small road block with flux calculations - the `apfit` value[1] is not output by tphorce and therefore not recorded in the ATLAS forced photometry database table.

I've [added the output to tphorce](https://github.com/thespacedoctor/tphorce/commit/24d04c1edaba34b1031ba753dc81ca70ea7e97ae) if you want to pull down the changes @genghisken 

I think I can retrospectively calculate `apfit` for the current forced photometry using values in the `atlas_detectionddc` table using the brightest sources for each exposure. Will need to wait for MySQL server to be started on psdb3 after this morning's reboot.

---

1. <https://github.com/thespacedoctor/tphorce/blob/master/tphorce#L201>

**Comment by thespacedoctor** [comment]
Here's the [ATLASnsw](http://www.pessto.org/marshall/transients/search?q=ATLAS17nsw) transient now plotted with combined flux & magnitude axes. Note:

- discover date is the first >5𝜎 detection
- all >3𝜎 measurements are recorded as detections and the nightly combined average of these detections is plotted
- all <3𝜎 detections are plotted separately (i.e. no averaging) in open circles

![ATLAS17nsw flux lightcurve plot][ATLAS17nsw flux lightcurve plot 27963350119]

[ATLAS17nsw flux lightcurve plot 27963350119]: https://farm5.staticflickr.com/4666/27963350119_4b5acef281_o.png

Most issues with generalising the lightcurve code (axis ranges etc) have been ironed out and have been rolled out to the marshall, although there remains an issue with rogue detections, for example [ATLAS17nzp](http://www.pessto.org/marshall/transients/search?q=ATLAS17nzp).

**Comment by thespacedoctor** [comment]
I think we're happy now with these plots - closing ticket.

**Comment by smarttgit** [comment]
Yes, these plots are excellent - suggest you notify ePESSTO that the requirements from Dublin (this plus the discovery date) are done and all good!
