### ISSUE TITLE
Correct the discovery dates for ATLAS

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/marshall_webapp_wiki#139]
The "discovery" date in the marshall is often the first >1sigma flux measurement by ATLAS, which is wrong. 

Record the first >=5 sigma detection as the "discovery date" 

Make it 5 sigma to be safe. 

This is high priority, as we are propagating incorrect discovery dates into ATels etc

**Comment by thespacedoctor** [comment]
The discovery date in the marshall is taken from the first known detection of the transient, regardless of which survey reported the detection. To make sure the discovery date from ATLAS is the first detection >5𝜎 I've set all ATLAS detections at >5𝜎 and limits below 5𝜎. The limits are recalculated within the marshall so are no longer dependent on the native ATLAS database settings for limits.

Here are a couple of examples of the fixes (lightcurves shown are those generated before the flux-scale plots are introduced) ...

## ATLAS18aap

### BEFORE:

![ATLAS18aap pre-lightcurve fix][ATLAS18aap pre-lightcurve fix 38681564795]

[ATLAS18aap pre-lightcurve fix 38681564795]: https://farm5.staticflickr.com/4684/38681564795_42da89f54c_o.png 

**discovery date**: 2017-12-16

### AFTER:

![ATLAS18aap post lightcurve fix][ATLAS18aap post lightcurve fix 39580149272]

[ATLAS18aap post lightcurve fix 39580149272]: https://farm5.staticflickr.com/4714/39580149272_7578c3abb7_o.png

**discovery date**:  2017-12-18

## ATLAS17nzu

### BEFORE:

![ATLAS17nzu pre-lightcurve fixes][ATLAS17nzu pre-lightcurve fixes 27801209559]

[ATLAS17nzu pre-lightcurve fixes 27801209559]: https://farm5.staticflickr.com/4589/27801209559_3ba43de102_o.png 

**discovery date**:  2017-11-25

### AFTER:

![ATLAS17nzu][ATLAS17nzu 27832091349]

[ATLAS17nzu 27832091349]: https://farm5.staticflickr.com/4651/27832091349_ff0338c4b7_o.png 

**discovery date**:  2017-12-25
