### ISSUE TITLE
OGLE lightcurve plots are poor in marshall tickets 

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/marshall_webapp_wiki#140]
OGLE lightcurve plots should be better. They are just points, with no error bars or upper limits. 

Plot with : 
1. Error bars
2. Any point which is <3sigma (from the OGLE error on mag) then plot as open circle, with the error bar. 
3. Any point which is >3sigma plot as a solid point with error bar
4. Add the upper limits. They seem to be all set at m = 22. But useful anyway to show when the field was observed even if 22 is optimistic 

Or for now, switch in the OGLE plot itself - which is visible under the photometry tab

**Comment by thespacedoctor** [comment]
light curve code was updated some time ago
