### ISSUE TITLE
Add ability to adjust URL to search for '-' NT

### ISSUE THREAD

**Issue by katemaguire** [thespacedoctor/marshall_webapp_wiki#145]

**Comment by katemaguire** [comment]
Thanks Dave!

**Comment by thespacedoctor** [comment]
Hi Kate,

Decided instead to add in the 'not equal to' option to the allowed `filterOp2` key values. For your use case you want to filter by those transients that are NOT NTs. Start by filtering whatever list you're interested in by transients with NT sherlock classification and then in the URL change `filterOp2=eq` to `filterOp2=neq`. Simples.

**Comment by thespacedoctor** [comment]
e.g. <http://www.pessto.org/marshall/transients?filterBy2=sherlockClassification&filterValue2=NT&filterOp2=neq>
