### ISSUE TITLE
AT2018sz wrong Sherlock match

### ISSUE THREAD

**Issue by katemaguire** [thespacedoctor/marshall_webapp_wiki#146]
This is matched to a Messier galaxy that is 4841.48" N, 766.57" E (16.4 Kpc) away but is much more likely associated with the SDSS galaxy SDSS J013450.70+320020.6 that it sits in. Maybe the SDSS galaxy wasn't picked up because its photometry on SDSS is flagged as unreliable?

**Comment by katemaguire** [comment]
Similar issue for AT2018tb

**Comment by thespacedoctor** [comment]
## AT2018sz

If you look at the context tab for the ticket you can see that the SDSS galaxy was picked up, but the M33 was ranked as the top match.

![screengrab][screengrab 40216987852]

[screengrab 40216987852]: https://farm5.staticflickr.com/4697/40216987852_026deaa450_o.png 

I think I can tweak the match-ranking algorithm to have the SDSS galaxy float above the NED result.

**Comment by katemaguire** [comment]
I guess it is tricky to get right in all circumstances and we don't want to miss the associations with very nearby galaxies. I don't know exactly what goes into the match-ranking algorithm but perhaps you could use the fact that the absolute magnitude of the transients would be very very bright if they were associated with the massive galaxies?

**Comment by thespacedoctor** [comment]
Yes I had considered this, but haven't had to resort to using the absolute magnitude as a ranking metric yet. I need to make sure I don't bias the code towards accurately classifying SNe at the expense of other types of transients/variables. This source could technically be a variable star in M33 at M = -4.4?

I think I still have some scope to more accurately rank matches based on physical & angular separations.

**Comment by thespacedoctor** [comment]
Updated sherlock ranking algorithm and reran for all transient in the marshall. AT2018sz is now associated best with the SDSS galaxy:

<http://www.pessto.org/marshall/transients/search?q=AT2018sz>

**Comment by thespacedoctor** [comment]
Update has also fixed AT2018tb:

<http://www.pessto.org/marshall/transients/search?q=AT2018tb>

You can close the issue if your happy!

**Comment by katemaguire** [comment]
Great looks good. Will let you know if I see any more.

**Comment by katemaguire** [comment]
Not sure if this updated since you changed the code or not but this one should be associated with the NED galaxy:
http://www.pessto.org/marshall/transients/search?q=AT2018rz

**Comment by thespacedoctor** [comment]
I'm afraid we're hitting an edge case here where it's going to be up to the user to decide which galaxy the transient is truly associated with. As you can see the transient is right on top of what SDSS thinks is a galaxy (but really just an extended mass in NGC 5618):

![screengrab][screengrab 39382200415]

[screengrab 39382200415]: https://farm5.staticflickr.com/4655/39382200415_70188c4fef_o.png 

<http://skyserver.sdss.org/dr14/en/tools/chart/navi.aspx?ra=216.797822105983&dec=-2.2695328034389&scale=0.2>

Catch 22 when considering the issue with the other 2 transients discussed above.

**Comment by katemaguire** [comment]
Hmm I can't decide which I think is better. In both cases (the previous two objects and this object), it was clear from the images and contextual info. that the wrong galaxy was listed first so probably not a major issue. It would be good to be able to change the galaxy so that the absolute magnitudes etc. update? Would it be too much freedom to give Marshall users the ability to be able to rerank?

**Comment by thespacedoctor** [comment]
add it as a separate enhancement issue and I'll try and code it up if I get time.

**Comment by katemaguire** [comment]
Ok will do. Thanks.
