### ISSUE TITLE
Snoozed objects keep appearing without any new data

### ISSUE THREAD

**Issue by katemaguire** [thespacedoctor/marshall_webapp_wiki#149]
A number of objects keep reappearing in the inbox after being snoozed. No new data seems to have been obtained so don't know why they're returning e.g.
AT2018up
AT2017jzf
AT2018li

**Comment by Lyalpha** [comment]
ATLAS18mkz has just reappeared also, having been classified. Doesn't look to have been new photometry taken to cause it to jump back to inbox.

**Comment by thespacedoctor** [comment]
I have refactored the resurrection code - but expect to need to iterate to hit a sweet-spot between silent and annoying.
