### ISSUE TITLE
Duplicate objects appearing in marshall

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/marshall_webapp_wiki#153]
2018ard has two entries in the marshall, one as AT2018ard and one as SN2018ard : 

http://www.pessto.org/marshall/transients/search?q=2018ard

this is causing some confusion, as observers have classified this again (since they see AT2018ard in the classification queue with no classification)

**Comment by thespacedoctor** [comment]
Both entries have been merged - including history and comments.

http://www.pessto.org/marshall/transients/search?q=2018ard
