### ISSUE TITLE
Duplicate objects appearing 

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/marshall_webapp_wiki#157]
kait-18T and AT2018bei are the same object with identical coordinates - but appear as two separate objects in marshall

**Comment by thespacedoctor** [comment]
There was an ongoing sql query clogging to the database which was making processes timeout. This resulted in:

- proxy error on viewing marshall
- proxy error on adding tickets
- this duplicate source as importer borked

I've merged this source:

http://www.pessto.org/marshall/transients/search?q=ATLAS18nnp

**Comment by thespacedoctor** [comment]
This is the same source as reported in #153 and #159
