### ISSUE TITLE
Ordering of objects in the classification queue

### ISSUE THREAD

**Issue by katemaguire** [thespacedoctor/marshall_webapp_wiki#160]
Request (from Michel) that the default ordering be priority (as it is now), but within the priorities to be order by 'date/time added to the classification queue'.

**Comment by thespacedoctor** [comment]
The default is to order by priority and then the secondary sort is RA. Would it be better to do a secondary sort on date added to marshall? I can’t give you date added to classification queue without a good but of work I’m afraid.

**Comment by thespacedoctor** [comment]
Reply from KM:

> Yeah I think date added to the Marshall would be better than RA. That way any new high priority objects would be at the very top of the ‘high priority’ list.

**Comment by thespacedoctor** [comment]
Does this work?:

http://www.pessto.org/marshall/transients?mwl=pending+observation

**Comment by katemaguire** [comment]
Yes, works for me. They’re now ordered by date added to the marshall. Thanks.
