### ISSUE TITLE
Duplicated ASASSN-18kp -> AT2018btr

### ISSUE THREAD

**Issue by Lightbulb500** [thespacedoctor/marshall_webapp_wiki#162]
More than likely another example of ASASSN updating their TNS co-ords

The information on the Marshall's entry is the correct version

http://www.pessto.org/marshall/transients/search?q=ASASSN-18kp

**Comment by thespacedoctor** [comment]
Yes - this time the coordinates were initially incorrect on their webpages, which I think are probably hand-written so easy to get copy-paste errors. As you can see the coordinates are completely different.

![screengrab][screengrab 41574064304]

[screengrab 41574064304]: https://farm1.staticflickr.com/894/41574064304_41b0b20acf_o.png

I've removed the faulty ticket
