### ISSUE TITLE
Rogue ASASSN-18qv entry in inbox

### ISSUE THREAD

**Issue by Lyalpha** [thespacedoctor/marshall_webapp_wiki#166]
ASASSN-18qv (SN 2018eph) is already in the marshall and has been classified (id 25800818). There is an inbox object with the same name (id 25810534) but wrong coordinates etc. Can't see where it came from.

**Comment by thespacedoctor** [comment]
Thanks Joe. The ASASSN pages are updated by hand I think and occasionally
they input incorrect coordinates or link the coordinates to the wrong
object. The marshall picks these up but isn't intelligent enough to go back
and pick up any corrections on the ASASSN page.

I've removed this duplicate entry.

closes #166

**Comment by Lyalpha** [comment]
Just a bit more info as another has just come in (http://www.pessto.org/marshall/transients/search?q=asassn-18re)
It seems to be misreading the columns - the decimal dec value in marshall is actually redshift in assasn page, similarly the mag is misread as abs mag. Perhaps they've done something to their table format, although only seems to be wrong on the duplicate entries? Probably just some cross-talk during the marshall checking whilst they insert new entries.

**Comment by thespacedoctor** [comment]
Thanks for the extra details Joe I've turned off the direct ASASSN imports for now, but they will come through via TNS.

Appreciate these bug reports!
