### ISSUE TITLE
Wrong non-detection date recorded in the Marshall for SN2018fnq

### ISSUE THREAD

**Issue by katemaguire** [thespacedoctor/marshall_webapp_wiki#168]
Non-detection looks to be 10 days before first detection, not 2 as the Marshall says

**Comment by thespacedoctor** [comment]
Slightly delayed reply ... 

The non-detection reported by the marshall is from the ASASSN via the TNS. It is buried in the photometry section on the TNS page:

[![](https://live.staticflickr.com/65535/51164249950_a80edd7f51_b.jpg)](https://live.staticflickr.com/65535/51164249950_a80edd7f51_b.jpg)

This is more a data-surfacing issue than a bug
