### ISSUE TITLE
ATLAS forced phot needs to reject outliers 

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/marshall_webapp_wiki#169]
There are too many of these getting through now to leave. It is causing trouble, in target selection, and the absolute mags at peak are way off, and causing confusion. 

Now have to fix 

Examples : 
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1024107930053339800/
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1024107930053339800/
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1055002160281312400/
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1054247870242934900/

We know the diffs are rogue in this, and we need to reject these. There must be an easy way fro simple rejection of these points, from either the image FITS headers or the DDC files (e.g. I think the zeropoint is way off - which is  an easy catch). 

The diff images have obviously gone wrong, just from eyeballing. 

Look at the ZPs first to see if that's an easy rejection  as :

if ZP < 17 then reject

Taking a median or clipped median will not work since these are often single detections on a night with 3 or 4 upper limits. 

But we need to give this highest priority now 

Submitted to ATLAS and Marshall. Really an ATLAS problem but marshall is working with forced and averaging these mags, which is were it is really causing users difficulties.

**Comment by thespacedoctor** [comment]
## ATLAS18uxj

Taking [ATLAS18uxj](http://www.pessto.org/marshall/transients/search?q=ATLAS18uxj) as the first example you can see the rogue datapoint throwing the lightcurve off at MJD~=58329:



![](https://farm2.staticflickr.com/1865/43848957835_e5aa0bdcba_o.png)

Querying the `ATLAS18uxj` forced photometry table in the marshall database, there are 254 datapoints (detections and limits):

```sql
SELECT 
    zp, mjd_obs, marshall_limiting_mag, marshall_mag
FROM
    fs_atlas_forced_phot
WHERE
    atlas_designation = 'ATLAS18uxj'
ORDER BY zp;
```

![](https://farm2.staticflickr.com/1859/29821729237_890fbdd8ab_o.png)

You can see the ZP for the rogue point is bright (21.8), but nowhere near 17th mag. Investigating other column data I found that `skyfit` is the culprit for this individual datapoint:

```sql
SELECT 
    zp, mjd_obs, marshall_limiting_mag, marshall_mag, skyfit, flux
FROM
    fs_atlas_forced_phot
WHERE
    atlas_designation = 'ATLAS18uxj'
ORDER BY skyfit;
```

![](https://farm2.staticflickr.com/1890/29821799937_abac69233d_o.png)



## ATLAS18ufi



Trying the same query with [`ATLAS18ufi`](http://www.pessto.org/marshall/transients/search?q=ATLAS18ufj) also reveals a negative `skyfit` with the rogue datapoint, and interestingly it too has a negative `flux` assigned:

![](https://farm2.staticflickr.com/1886/42948403650_507bebd9fc_o.png)

![](https://farm2.staticflickr.com/1899/29821949427_6d7c56303e_o.png)



## ATLAS18uto

Finally [`ATLAS18uto`](http://www.pessto.org/marshall/transients/search?q=ATLAS18uto):

![](https://farm2.staticflickr.com/1881/44758340131_773aab27a2_o.png)

Again we find a negative `skyfit` and `flux`:

![](https://farm2.staticflickr.com/1885/44709374912_2b06fc758d_o.png)



## Summary and A Fix

Query the entire forced photometry table for entries with negative `flux` & negative `skyfit` reveals 6136 datapoints (out of a total of 733,891; i.e. **0.8%**). Of these points only 928 are 'detections' and the others are limiting magnitudes.

```sql
SELECT 
    zp, mjd_obs, marshall_limiting_mag, marshall_mag, skyfit, flux
FROM
    fs_atlas_forced_phot
WHERE
    skyfit < 0 and flux < 0;
```

I've altered the marshall ATLAS lightcurve code to ignore these rogue data points and the lightcurves now look better:

![](https://farm2.staticflickr.com/1866/30892091688_2c4ed36900_o.png)

![](https://farm2.staticflickr.com/1854/30892147458_aebf9655f4_o.png)

![](https://farm2.staticflickr.com/1851/29825853077_3f289ea2c8_o.png)

I need to further investigate the other data points throwing the curves off for ATLAS18ufi and ATLAS18uto.

**Comment by genghisken** [comment]
Good job.  I came to the same conclusion re: unable to use ZP.

Meanwhile here's a real WTF object...  What happens if you apply your solution?

ATLAS18vim: https://star.pst.qub.ac.uk/sne/atlas4/candidate/1223215450234712600/

**Comment by thespacedoctor** [comment]
Given a second look at the data for these lightcurves it turns out that *any* detection with a measured negative `skyfit` results in throwing the `flux` way off. 2191 measured fluxes have an associated negative flux, so still a small subset of all the ATLAS force photometry.

I have regenerated the plots ignoring any data points with a negative  `skyfit` and ATLAS18uto shows a much better lightcurve:



![](https://farm2.staticflickr.com/1848/30932076028_9d7068b7b6_o.png)

ATLAS18ufj however still seems to display a single rouge point at just brighter than 17th mag:

![](https://farm2.staticflickr.com/1846/44803151261_cf44c911b2_o.png)

There is nothing untoward in the forced photometry table to indicate why this world be the case. 

I'm going to roll out the negative  `skyfit`  filter across all ATLAS transients in the marshall database, force a regeneration of all the lightcurves and eyeball them to see if this largely patches the rogue data problem.

Of-course it would be good to get a fix for this in the original code so as not to lose forced-photometry data.

**Comment by thespacedoctor** [comment]
## ATLAS18vim

With the negative  `skyfit`  filter ATLAS18vim went from this:



![](https://farm2.staticflickr.com/1875/44752684132_7992afb882_o.png)

to this:



![](https://farm2.staticflickr.com/1877/42993019580_a5933aa7c2_o.png)

There are obviously still issues with a few of the data points, but I think these may be specific to this object. Could there be a bleed over from the star to the north-east or a diffraction spike from the star to the south contaminating the forced phot?

![](https://farm2.staticflickr.com/1864/44102753684_9e86bff178_o.png)

**Comment by thespacedoctor** [comment]
Scanning the regenerated lightcurves for the latest 100 ATLAS objects in the marshall reveals there is still an unacceptable number of sources were a rogue datapoint is throwing the lightcurves off.

[ATLAS18vim](http://www.pessto.org/marshall/transients/search?q=ATLAS18vim)
[ATLAS18vij](http://www.pessto.org/marshall/transients/search?q=ATLAS18vij)
[ATLAS18vio](http://www.pessto.org/marshall/transients/search?q=ATLAS18vio)
[ATLAS18vgq](http://www.pessto.org/marshall/transients/search?q=ATLAS18vgq)
[ATLAS18vga](http://www.pessto.org/marshall/transients/search?q=ATLAS18vga)
[ATLAS18vew](http://www.pessto.org/marshall/transients/search?q=ATLAS18vew)
[ATLAS18uyw](http://www.pessto.org/marshall/transients/search?q=ATLAS18uyw)
[ATLAS18uxd](http://www.pessto.org/marshall/transients/search?q=ATLAS18uxd)
[ATLAS18uoj](http://www.pessto.org/marshall/transients/search?q=ATLAS18uoj)
[ATLAS18tgw](http://www.pessto.org/marshall/transients/search?q=ATLAS18tgw)
[ATLAS18ule](http://www.pessto.org/marshall/transients/search?q=ATLAS18ule)
[ATLAS18uld](http://www.pessto.org/marshall/transients/search?q=ATLAS18uld)

Continuing to dig in deeper.

**Comment by thespacedoctor** [comment]
Here's another:

http://www.pessto.org/marshall/transients/26597190

**Comment by thespacedoctor** [comment]
Another one:

http://www.pessto.org/marshall/transients/search?q=ATLAS18vim

**Comment by thespacedoctor** [comment]
I now have some new code (written for the ATLAS FP server). I need to switch out the old ATLAS LC plotting code with the newer code that does a far better job of cleaning the data.

**Comment by thespacedoctor** [comment]
I have now integrated the new ATLAS plotting code into the marshall and replotted all FP data. Here's a good example from one of the objects highlighted above (ATLAS18wcg):

[![](https://live.staticflickr.com/65535/51161151321_d8be05e28b_z.png)](https://live.staticflickr.com/65535/51161151321_d8be05e28b_o.png)
