### ISSUE TITLE
ATLAS photometry not propagting to marshall ? 

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/marshall_webapp_wiki#171]
Seems like ATLAS stamps and lightcurves/photometry has stopped being ingested  

e.g 
http://www.pessto.org/marshall/transients/search?q=2019fxy

**Comment by thespacedoctor** [comment]
I've had to stop panstarrs, atlas and ztf ingestions while I rewrite the import codes to be lighter on the database. These imports were the cause of the many timeouts and locks 2 sub-runs ago. Transients are still getting through via TNS. Hope to be fixed soon.
