### ISSUE TITLE
Marshall alerts for previously classified transients on TNS

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/marshall_webapp_wiki#173]
Just FYI - I just spotted that the Marshall doesn't seem to alert observers if a classification spectrum already exists in TNS for an object.

E.g. 2019oet was in the classification queue. If there is an ATel, users are normally alerted to this, but in this case there was no ATel (or even an AstroNote) - just a spectrum on TNS.

**Comment by thespacedoctor** [comment]
It should do! Need to check - TNS importer had stalled last night, may have done so again.

cheers,
Dave

Dr. David Young (Scientific Programmer)
e:
d.r.young@qub.ac.uk
a:
Astrophysics Research Centre, School of Mathematics and Physics,
Queen's University Belfast, Belfast, BT7 1NN, UK
t:
(028) 90971442
w:
http://www.astronotes.co.uk
gh:
@thespacedoctor

**Comment by thespacedoctor** [comment]
this guy was the LBV and so did not get a SN designation - my logic to pull the classifications currently relies on that 'SN'. Will change.

**Comment by thespacedoctor** [comment]
The new TNS parser has been running on the marshall over the weekend. It caught this guy, and added the classification.
