### ISSUE TITLE
Proxy errors and internal server errrors 

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/marshall_webapp_wiki#175]
When classifying, the marshall hung up and gave 

Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request POST /marshall/transients/40216946.

Reason: Error reading from remote server

but the classification went through. But now when I try to re-classify, 
http://www.pessto.org/marshall/transients/search?q=AT2019zel

I get : 

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, [no address given] and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

**Comment by smarttgit** [comment]
Want to re-classify to "unknown"

**Comment by thespacedoctor** [comment]
I isolated the underlying issue causing the proxy & internal errors but need a couple of unbroken hours to fix. Issue affects user-added classifications and new tickets. 

In the short-term I've updated the classification for AT2019zel by forcing it through:

http://www.pessto.org/marshall/transients/search?q=AT2019zel

**Comment by thespacedoctor** [comment]
Fixed
