### ISSUE TITLE
Change order in “all targets” queue

### ISSUE THREAD

**Issue by janetstars** [thespacedoctor/marshall_webapp_wiki#180]
Hi Dave,

This run’s observer reports a question about the marshall “all targets” queue.
When use the sort function of priority, they see:
high > critical > medium > important > low > useful > none.

Can we change the order to:
critical > high > important > medium > useful > low > none?

In principle, the followup targets have higher priority than classification targets. 
So it would be helpful for observers to make a night plan with correct oder when using “all targets” queue.

Thank you,
Janet

**Comment by thespacedoctor** [comment]
This change should now be live. See:

https://www.pessto.org/marshall/transients?filterBy1=False&filterValue1=30&filterOp1=%3C&listName=%3D+all&mwl=allObsQueue&limit=100&pageStart=0&format=plain_table&sortBy=observationPriority&sortDesc=False&ticketLimit=10&tableLimit=100&filterBy2=False&filterValue2=False&filterOp2=%3D&filterText1=&filterText2=&method=get
