### ISSUE TITLE
Object missing ATLAS Forced Photometry

### ISSUE THREAD

**Issue by mFulton07** [thespacedoctor/marshall_webapp_wiki#181]
This ALTAS object appears to be missing the ATLAS forced photometry on the Marshall (added on the 3rd of December). Not sure what has happened, have checked over other ATLAS objects reported on the same day and they seem to have the forced photometry, so the issue might be specific to this one object.

Find the object here: https://www.pessto.org/marshall/transients/search?q=2021agce

**Comment by thespacedoctor** [comment]
fixed
