### ISSUE TITLE
Date in the comment

### ISSUE THREAD

**Issue by cinserra** [thespacedoctor/marshall_webapp_wiki#49]
It is a really minor improvement but together with the time passed since the latest comment (in light green in the comment section of an object), you could also think to add the date when the comment was written since at times observers forget to write when an object was observed. It would be easier if we also had the date of the comment.

![screen shot 2014-12-10 at 16 08 58](https://cloud.githubusercontent.com/assets/9800994/5379187/4402e8f6-8087-11e4-935c-8fc0773f5bbd.png)

**Comment by thespacedoctor** [comment]
If a comment is < 14 days old then a relative date is shown, but if older than 14 days an absolute date is now shown.

![](http://i.imgur.com/5ynjZXe.png)

Will appear in next release.
