### ISSUE TITLE
LSQ discovery date

### ISSUE THREAD

**Issue by cinserra** [thespacedoctor/marshall_webapp_wiki#55]
In the marshall the reported LSQ discovery date seems to be the first detection of the re-calibrated light curve that it is not the discovery epoch reported by LSQ in the ATels and in the history of each single object (they usually wait one or two detections and sometimes the discovery date in the marshall is different than that reported in LSQ web pages)

**Comment by thespacedoctor** [comment]
The first detection from the re-calibrated light curve is the 'true' discovery date and the most meaningful for us. The discovery date reported in the LSQ histories is date they first detected the object before they returned to do forced photometry.

I will not change this unless there is popular demand to do us.
