### ISSUE TITLE
Clear Gaia and classified iPTF (etc) targets from the inbox Link: x-dispatch://david.young@pessto.org/%3cF262FEBA-72A8-4ADA-937D-40CB68297138%40qub.ac.uk%3e

### ISSUE THREAD

**Issue by thespacedoctor** [thespacedoctor/marshall_webapp_wiki#68]

**Comment by smarttgit** [comment]
This is done - they were being ingested from bright supernova page. But now turned off.

**Comment by thespacedoctor** [comment]
I've actually converted the BSL to an 'external source' list, much like the ATels. Objects in the BSL are imported into a separate table in the marshall database. The relevant BSL data is then only imported into the main table if and when the object is discovered by one of our feeder surveys. 

The benefit of this is that we collect all possible AKAs and image stamps recorded in the BSL get imported into the marshall.
