### ISSUE TITLE
two lines with options on the top of the page

### ISSUE THREAD

**Issue by svalenti** [thespacedoctor/marshall_webapp_wiki#88]
when I search for a transient that is not there, I get a double line on the top. see attachment

<img width="1419" alt="screen shot 2015-07-11 at 9 38 07 am" src="https://cloud.githubusercontent.com/assets/7798941/8634522/ea02c0b6-27b0-11e5-9549-3f2de67d7944.png">

**Comment by thespacedoctor** [comment]
I've added a comment and icon to show the user that no match has been made:

![screengrab][screengrab 40063271102]

[screengrab 40063271102]: https://farm5.staticflickr.com/4622/40063271102_afda98afdb_o.png

Should be clearer now.
