### ISSUE TITLE
ASASSN-15hy has wrong classification

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/marshall_webapp_wiki#90]
should be Ia (peculiar) from ATel 7452. Don't know why it is "Unk"

**Comment by smarttgit** [comment]
Also ASASSN-15hx is listed wrong too. Should be a Ia at -11d

**Comment by thespacedoctor** [comment]
both fixed.

The classifications were changed to "unk" because at some point the classification on the ASASSN pages was switched to "unk". This was imported into the marshall and new classifications "trump" previous classifications.

I've written a catch into the import code to try and stop this in the future.

**Comment by smarttgit** [comment]
Also ....
ASASSN-15hz
ASASSN-15hs 
Although these were classified by WiFES in ATel 7458, the classification should be corrected in our marshall. 

And looking down, there are  a lot more targets that in the "review for follow-up" list but which have no 
types. Don't know how or why they ended up in this list without types. PESSTO didn't classify them, 
but they are classified, so for the record we should have their types in the database (in case of 
coincidences etc). I've gone through manually : 

ASASSN-15ir   type=II http://www.astronomerstelegram.org/?read=
ASASSN-15jl type=Ia in http://www.astronomerstelegram.org/?read=7535
ASASSN-15jm type=Ia in http://www.astronomerstelegram.org/?read=7550
ASASSN-15jo type=Ia http://www.astronomerstelegram.org/?read=7553
ASASSn-15jp  type = II  http://www.astronomerstelegram.org/?read=7557 
ASASSN-15js  type =Ia http://www.astronomerstelegram.org/?read=7609
ASASSN-15ke type=Ia http://www.astronomerstelegram.org/?read=7573 (iPTF15apg)
ASASSN-15kg type=Ia peculiar http://www.astronomerstelegram.org/?read=7590
ASASSN-15kj  type=Ic  http://www.astronomerstelegram.org/?read=7692
ASASSN-15kq type=Ia http://www.astronomerstelegram.org/?read=7613
ASASSN-15kn= PSNJ12415045-0710122  type=Ia http://www.astronomerstelegram.org/?read=7610
ASASSN-15kx  type=Ia  http://www.astronomerstelegram.org/?read=7623
ASASSN-15ji  type=Ia http://www.astronomerstelegram.org/?read=7640
ASASSN-15lv type=IIb http://www.astronomerstelegram.org/?read=7746
ASASSN-15mc type=Ia http://www.astronomerstelegram.org/?read=7803
ASASSN-15mi type=Ia http://www.astronomerstelegram.org/?read=7796
ASASSN-15mj   type=Ib http://www.astronomerstelegram.org/?read=7821
ASASSN-15ml  type=Ia http://www.astronomerstelegram.org/?read=7802
ASASSN-15mp type=Ia http://www.astronomerstelegram.org/?read=7817
ASASSN-15ms type=Ia http://www.astronomerstelegram.org/?read=7826
ASASSN-15mx type=Ia http://www.astronomerstelegram.org/?read=7824

This one is  not classified as far as I can see and should not be in the "review for follow-up" put back into inbox
ASASSN-15mq

**Comment by thespacedoctor** [comment]
Thanks, I was fixing these as you wrote! This is the same issue. I lift the classifications from the ASASSN pages:

http://www.astronomy.ohio-state.edu/~assassin/sn_list.html

If you look near the bottom of the page there are objects classified as "Unk". The fix to the import code should stop this in the future. All the objects are back in the inbox and I'll walk through and classify them now.

**Comment by thespacedoctor** [comment]
all classifications added - closing for now
