### ISSUE TITLE
The link to PS targets does not go to our object pages

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/marshall_webapp_wiki#91]
Live links on the tickets for PS objects should link directly to the object pages - they currently go to the Bright SN page. Needs an urgent fix.

**Comment by thespacedoctor** [comment]
PS objects get added in one of two ways:
1. Ken pushes a "good" PS object into the marshall via our import scripts - the object is then assigned the PS URL
2. An object is discovered by a survey other than PS, lets say LSQ. The LSQ object gets added to the marshall and if the bright SN list has an alternative name for the LSQ object, it gets added as an AKA. If the AKA is a PS object and Ken hasn't pushed the object to the marshall via step 1, then the bright SN list URL is added.

I've written a name/URL switcher to change the URL from the bright SN list URL to another survey where possible, but this doesn't solve the issue above.

A suggested fix would be for Ken to add ALL of the publicly released PS objects into the marshall automatically and allow the TAT to weed out the interesting objects. Once these objects get into the marshall, the name/URL switcher would then switch the URLs
