### ISSUE TITLE
Status of object on ticket needs added - after object search

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/marshall_webapp_wiki#92]
When you search for, and find an object, the ticket pops up. But then you don't know which queue it is in. It would be really useful to see immediately where it is. So a line of text (probably bottom right) saying, 
"Currently in the $queue"

This is quite high priority - have been meaning to add for some time 

where 
$queue = one of ..... 
                inbox
                review for follow-up
                classification targets
                follow-up targets
                queued for classification
                queued for ATel
                follow-up complete
                archive

**Comment by smarttgit** [comment]
OK - I can see its status in "ticket history" 

that's fine - no longer priority1, as the info is there and accessible. Would be nice to have in ticket body itself for quick and immediate overview, but higher priority things. Keep on list but low priority.

**Comment by thespacedoctor** [comment]
Added this in while creating the 'snooze' list feature:

![](https://i.imgur.com/P5MwhV4.png)

You can find the host list in the identification block of each ticket.
